### ISSUE TITLE
[Patterns] Component Generation

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-traefik-mesh#121]
**Description**
Component generation is failing.

**Expected Behavior**
Components should dynamically generate and register with Meshery Server

**Screenshots/Logs**
```
time="2021-09-29T17:48:14Z" level=info msg="Listing Operations" app=traefik-mesh-adaptor
time="2021-09-29T17:48:14Z" level=info msg="Creating instance" app=traefik-mesh-adaptor
time="2021-09-29T21:10:46Z" level=info msg="Adaptor Listening at port: 10006" app=traefik-mesh-adaptor
time="2021-09-29T21:10:46Z" level=info msg="lstat /.meshery/templates/oam/traits: no such file or directory" app=traefik-mesh-adaptor
time="2021-09-29T21:10:48Z" level=info msg="Registering latest workload components for version v1.3.2" app=traefik-mesh-adaptor
Looking for kubeopenapi-jsonschema in  /root/.meshery/bin
time="2021-09-29T21:10:49Z" level=info msg="exit status 1" app=traefik-mesh-adaptor
time="2021-09-29T21:11:24Z" level=info msg="Creating instance" app=traefik-mesh-adaptor
time="2021-09-29T21:11:24Z" level=info msg="Listing Operations" app=traefik-mesh-adaptor
```

<img width="400" alt="Screen Shot 2021-09-29 at 4 12 28 PM" src="https://user-images.githubusercontent.com/7570704/135350564-b98fc1dd-0725-48eb-82ae-fc22f9cc4f13.png">

**Environment:**
- Meshery Version: v0.5.62
- Adapter Version: v0.5.10

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Revolyssup** [comment]
@leecalcote  check and confirm if this still fails after my most recent PR. It works as expected on my system

**Comment by Revolyssup** [comment]
@leecalcote  After the latest PR:
![demo](https://user-images.githubusercontent.com/43276904/135610200-185f885c-bb96-4c4a-8572-0931a573ff3d.png)

**Comment by warunicorn19** [comment]
<img width="1440" alt="Screenshot 2021-10-01 at 5 02 26 PM" src="https://user-images.githubusercontent.com/53532328/135613119-6b712350-c909-4310-9eee-230f3661c564.png">

 i can see only v1.3.2 on mine

**Comment by Revolyssup** [comment]
> <img alt="Screenshot 2021-10-01 at 5 02 26 PM" width="1440" src="https://user-images.githubusercontent.com/53532328/135613119-6b712350-c909-4310-9eee-230f3661c564.png">
> 
> i can see only v1.3.2 on mine

My pr is not merged. 
Are you doing gh checkout on this PR?

**Comment by warunicorn19** [comment]
Oh no sorry, my bad, I thought it was merged.

**Comment by Revolyssup** [comment]
This issue was solved
