### ISSUE TITLE
[bug] adapter panics when deploying

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery-traefik-mesh#123]
#### Current Behavior
The adapter gets deployed but panics and dies.

#### Expected Behavior
Adapter should not panic and work.

#### Screenshots/Logs
```
time="2021-09-30T20:32:05Z" level=info msg="Adaptor Listening at port: 10006" app=traefik-mesh-adaptor
time="2021-09-30T20:32:05Z" level=info msg="lstat /.meshery/templates/oam/traits: no such file or directory" app=traefik-mesh-adaptor
time="2021-09-30T20:32:07Z" level=info msg="Registering latest workload components for version v1.3.2" app=traefik-mesh-adaptor
Looking for kubeopenapi-jsonschema in  /root/.meshery/bin
panic: runtime error: index out of range [0] with length 0

goroutine 32 [running]:
github.com/layer5io/meshkit/utils/manifests.getApiVersion(0xc00081d590, 0x29, 0xc000ab86a0, 0x1c, 0xc0009ee1c2, 0xd, 0x1bf5ff3, 0x4, 0x1c0157f, 0xc, ...)
        /go/pkg/mod/github.com/layer5io/meshkit@v0.2.29/utils/manifests/utils.go:172 +0x772
github.com/layer5io/meshkit/utils/manifests.getDefinitions(0xc0009ee1c2, 0xd, 0x0, 0x1c0157f, 0xc, 0xc0006a23c0, 0x6, 0xc0006c9bc0, 0x1, 0x1, ...)
        /go/pkg/mod/github.com/layer5io/meshkit@v0.2.29/utils/manifests/utils.go:22 +0x198
github.com/layer5io/meshkit/utils/manifests.GenerateComponents(0xc000ac0600, 0x5d6, 0x0, 0x1c0157f, 0xc, 0xc0006a23c0, 0x6, 0xc0006c9bc0, 0x1, 0x1, ...)
        /go/pkg/mod/github.com/layer5io/meshkit@v0.2.29/utils/manifests/generateComponent.go:87 +0x4b8
github.com/layer5io/meshkit/utils/manifests.GetFromHelm(0xc0007d33b0, 0x2c, 0x0, 0x1c0157f, 0xc, 0xc0006a23c0, 0x6, 0xc0006c9bc0, 0x1, 0x1, ...)
        /go/pkg/mod/github.com/layer5io/meshkit@v0.2.29/utils/manifests/getComponents.go:25 +0xb8
github.com/layer5io/meshery-adapter-library/adapter.RegisterWorkLoadsDynamically(0xc000044baf, 0x13, 0xc000940e20, 0x1a, 0xc000717e08, 0x1bf6290, 0x5)
        /go/pkg/mod/github.com/layer5io/meshery-adapter-library@v0.1.24/adapter/oam.go:176 +0x79f
main.registerWorkloads(0x1bf6290, 0x5, 0x1e68200, 0xc0000100c0)
        /build/main.go:184 +0x4fa
main.registerDynamicCapabilities(0x1bf6290, 0x5, 0x1e68200, 0xc0000100c0)
        /build/main.go:165 +0x4d
created by main.main
        /build/main.go:114 +0x6ce
```

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by DelusionalOptimist** [comment]
@Revolyssup looks like pattern generation of pattern components failed.

**Comment by Revolyssup** [comment]
> @Revolyssup looks like generation of pattern components failed.

This is because, meshkit is upgraded to latest version but the changes are not reflected in adapter. Creating the PR, wait
