### ISSUE TITLE
 [CI] Patterns: Generate JSON Schema and Definitions for Traefik-mesh components #55 

### ISSUE THREAD

**Issue by Shreyas220** [meshery/meshery-traefik-mesh#129]
### Enhancement Description

To generate the workflow of getting the manifest from the Traefik-mesh using the [kubeopenapi-jsonschema](https://github.com/layer5io/kubeopenapi-jsonschema) to read and generate JSON schemas from those manifests and then also generating workload definitions from those schemas.

A sample workflow is [here](https://github.com/DelusionalOptimist/meshery-istio/blob/gen-oam/.github/workflows/update-oam-defs.yml)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the master branch.

**Comment by sayantan1413** [comment]
@Shreyas220 I guess the link for the crd will be of traefik-mesh.
