### ISSUE TITLE
Traefik Mesh Adapter not successfully registering

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-traefik-mesh#158]
#### Current Behavior
In v0.6.0-rc-4, this adapter's logs state that it has registered with Meshery Server. Meshery Server, though, shows no signs of this registration either in the UI or in the `/api/system/adapters` response.

#### Adapter Logs

```
➜  ~ k logs -n meshery meshery-traefik-mesh-59c748d8f4-n96x5
time="2022-01-19T22:39:07Z" level=info msg="Adaptor Listening at port: 10006" app=traefik-mesh-adaptor
time="2022-01-19T22:39:07Z" level=info msg="lstat /.meshery/templates/oam/traits: no such file or directory" app=traefik-mesh-adaptor
time="2022-01-19T22:39:08Z" level=info msg="Registering latest workload components for version 2.5.6" app=traefik-mesh-adaptor
Looking for kubeopenapi-jsonschema in  /root/.meshery/bin
time="2022-01-19T22:39:14Z" level=info msg="Latest workload components successfully registered." app=traefik-mesh-adaptor
```

#### Screenshot

<img width="470" alt="Screen Shot 2022-01-19 at 3 48 48 PM" src="https://user-images.githubusercontent.com/7570704/150230260-345192da-04f6-47cf-8ace-2d0595345263.png">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
We're in need of logs being shown in Meshery Server's output to document adapter interactions.

**Comment by Revolyssup** [comment]
> We're in need of logs being shown in Meshery Server's output to document adapter interactions.

Registeration is orthogonal to this issue. Registeration is successful, I checked it. The adapter is not reachable from UI because of some other reason, (gRPC call is failing). I am looking into it

**Comment by Revolyssup** [comment]
@leecalcote  Service is configured with wrong port. Will be making a PR in meshery

**Comment by Revolyssup** [comment]
@leecalcote  https://github.com/meshery/meshery/pull/4970 this will fix it

**Comment by leecalcote** [comment]
Nice work. :)
