### ISSUE TITLE
[Readme] Consistently present Meshery logo 

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery-traefik-mesh#224]
**Current Situation**
A brief description of what the current circumstance is.

As you see the current logo is quite big and is not consistent. 
**Desired Situation**
A brief description of the necessary action to take.

Make it consistent with github.com/meshery/meshery 's readme logo.

---
**Contributor Resources**
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by XDRAGON2002** [comment]
Hey @legendarykamal I would like to work on this!

**Comment by legendarykamal** [comment]
sure @XDRAGON2002
