### ISSUE TITLE
Broken image in Welcome message

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-traefik-mesh#230]
#### Current Behavior
The workflow that comments on first-time contributor PR merges has a broken image link. See https://github.com/meshery/meshery-traefik-mesh/pull/222#issuecomment-1268750343 for an example.

#### Screenshots/Logs

<img width="827" alt="Screen Shot 2022-10-05 at 12 52 33 PM" src="https://user-images.githubusercontent.com/7570704/194128517-65ae54ee-6e40-4fe6-b1a1-e6ff737c0f9b.png">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by amit-ksh** [comment]
I like to do this one

**Comment by Simba-97** [comment]
Hi @leecalcote I would like to work on this issue.

**Comment by leecalcote** [comment]
Swooped up by @amit-ksh with 26 seconds to spare.

**Comment by amit-ksh** [comment]
https://github.com/meshery/meshery/blob/master/.github/assets/images/Layer5-celebration.png Is this link the correct one?

**Comment by legendarykamal** [comment]
@Simba-97 I feel a little pity for you, there are more to come . Lets make sure you get your hands with something 😄.

**Comment by Simba-97** [comment]
@legendarykamal Sure. I'll definitely get my hands on something to contribute to layer5. 😄
